version: '3'

services:
  nginx:
    container_name: swc_nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: swc_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: swc
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - swc_db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  php:
    container_name: swc_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/application
    working_dir: /application
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    user: "1000:1000"

volumes:
  swc_db_data:
